-- 로컬 통합 검증 전용 최소 스키마.
-- 운영 Supabase에 적용하지 않는다. 저장소에 누락된 초기 테이블을 로컬에서만 재현한다.

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  ip text null,
  user_id uuid null references auth.users(id) on delete set null,
  date date not null,
  symbol text null,
  mentor_id text null,
  created_at timestamptz not null default now()
);
create index if not exists ai_usage_date_idx on public.ai_usage (date);
create index if not exists ai_usage_user_date_idx on public.ai_usage (user_id, date);
alter table public.ai_usage enable row level security;
create policy "local ai_usage select" on public.ai_usage for select using (true);
create policy "local ai_usage insert" on public.ai_usage for insert with check (true);

create table if not exists public.gemini_key_usage (
  id bigint generated by default as identity primary key,
  key_index integer not null,
  date date not null,
  created_at timestamptz not null default now()
);
alter table public.gemini_key_usage enable row level security;
create policy "local gemini usage all" on public.gemini_key_usage for all using (true) with check (true);

create table if not exists public.api_calls (
  id bigint generated by default as identity primary key,
  endpoint text not null,
  user_key text not null,
  user_id uuid null references auth.users(id) on delete set null,
  ip text null,
  status smallint not null,
  latency_ms integer null,
  error_code text null,
  created_at timestamptz not null default now()
);
create index if not exists api_calls_user_endpoint_time_idx on public.api_calls (user_key, endpoint, created_at desc);
create index if not exists api_calls_created_at_idx on public.api_calls (created_at desc);
alter table public.api_calls enable row level security;
create policy "local api_calls select" on public.api_calls for select using (true);
create policy "local api_calls insert" on public.api_calls for insert with check (true);

create table if not exists public.api_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  symbol text null,
  user_id uuid null references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table public.api_logs enable row level security;
create policy "local api_logs select" on public.api_logs for select using (true);

create table if not exists public.user_portfolios (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stocks jsonb not null default '[]'::jsonb,
  daily_snapshots jsonb not null default '[]'::jsonb,
  portfolio_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.user_portfolios enable row level security;
create policy "local portfolio own" on public.user_portfolios for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant usage on schema public to anon, authenticated;
grant select, insert on public.ai_usage, public.gemini_key_usage, public.api_calls to anon, authenticated;
grant select on public.api_logs to anon, authenticated;
grant select, insert, update, delete on public.user_portfolios to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
