-- AI 호출별 실제 토큰·원가·지연시간 원장.
-- 프롬프트/응답 원문과 API 키는 저장하지 않는다.
create table if not exists public.ai_cost_ledger (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  feature text not null,
  provider text not null check (provider in ('gemini', 'claude')),
  model text not null,
  user_id uuid null references auth.users(id) on delete set null,
  input_tokens integer not null default 0 check (input_tokens >= 0),
  output_tokens integer not null default 0 check (output_tokens >= 0),
  cached_input_tokens integer not null default 0 check (cached_input_tokens >= 0),
  reasoning_tokens integer not null default 0 check (reasoning_tokens >= 0),
  estimated_cost_usd numeric(14, 8) not null default 0 check (estimated_cost_usd >= 0),
  latency_ms integer not null default 0 check (latency_ms >= 0),
  cache_hit boolean not null default false,
  success boolean not null default true,
  error_code text null
);

create index if not exists ai_cost_ledger_created_at_idx
  on public.ai_cost_ledger (created_at desc);
create index if not exists ai_cost_ledger_feature_created_at_idx
  on public.ai_cost_ledger (feature, created_at desc);
create index if not exists ai_cost_ledger_user_created_at_idx
  on public.ai_cost_ledger (user_id, created_at desc)
  where user_id is not null;

alter table public.ai_cost_ledger enable row level security;

-- 클라이언트 직접 접근은 허용하지 않는다. 서버의 service role만 기록·조회한다.
revoke all on table public.ai_cost_ledger from anon, authenticated;
revoke all on sequence public.ai_cost_ledger_id_seq from anon, authenticated;
grant select, insert on table public.ai_cost_ledger to service_role;
grant usage, select on sequence public.ai_cost_ledger_id_seq to service_role;
