-- 주비 도구형 PRO 내부 기반. 결제 기능을 활성화하지 않으며 운영 적용은 파운더 승인 후 수행한다.
-- 투자 관련 AI 접근량·품질·속도는 profiles.tier와 무관하게 동일해야 한다.

alter table public.profiles
  add column if not exists pro_until timestamptz,
  add column if not exists pro_source text not null default 'none',
  add column if not exists plan_id text;

alter table public.profiles
  drop constraint if exists profiles_pro_source_check;
alter table public.profiles
  add constraint profiles_pro_source_check
  check (pro_source in ('none', 'manual', 'trial', 'billing'));

update public.profiles
set pro_source = 'manual'
where tier = 'pro' and pro_source = 'none';

create table if not exists public.subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  plan_id text not null,
  provider text not null,
  provider_customer_id text,
  provider_subscription_id text,
  status text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'expired')),
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean not null default false,
  canceled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists subscriptions_provider_id_unique
  on public.subscriptions (provider, provider_subscription_id)
  where provider_subscription_id is not null;
create index if not exists subscriptions_user_status_idx
  on public.subscriptions (user_id, status, current_period_end desc);

alter table public.subscriptions enable row level security;
drop policy if exists subscriptions_self_select on public.subscriptions;
create policy subscriptions_self_select on public.subscriptions
  for select using (auth.uid() = user_id);
-- INSERT/UPDATE/DELETE 정책은 만들지 않는다. 검증된 결제 웹훅의 service role만 변경한다.

create table if not exists public.billing_events (
  id bigint generated by default as identity primary key,
  provider text not null,
  event_id text not null,
  event_type text not null,
  payload_hash text not null,
  status text not null default 'received' check (status in ('received', 'processed', 'ignored', 'failed')),
  error_code text,
  received_at timestamptz not null default now(),
  processed_at timestamptz,
  unique (provider, event_id)
);

alter table public.billing_events enable row level security;
-- 사용자 정책 없음: service role 전용 멱등성·감사 테이블. 원문 결제 payload는 저장하지 않는다.

comment on table public.subscriptions is
  '비투자 관리 도구 구독 상태. AI 분석·시장 설명·시세 속도 차등에 사용 금지.';
comment on table public.billing_events is
  '결제 웹훅 중복 방지와 처리 감사. 개인정보가 포함될 수 있는 원문 payload 저장 금지.';
