-- 익명화된 AI 최종 출력 표본과 자동 컴플라이언스 플래그.
-- 사용자 ID, 프롬프트, 보유수량, 평단, 사용자 메모는 저장하지 않는다.
create table if not exists public.ai_output_audits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  feature text not null check (feature in ('ai-analysis', 'ai-chok')),
  symbol text null,
  output jsonb not null,
  source_snapshot jsonb null,
  flags text[] not null default '{}',
  severity text not null default 'none' check (severity in ('none', 'review', 'high')),
  reviewed_at timestamptz null,
  review_note text null
);

create index if not exists ai_output_audits_created_at_idx
  on public.ai_output_audits (created_at desc);
create index if not exists ai_output_audits_severity_created_at_idx
  on public.ai_output_audits (severity, created_at desc);

alter table public.ai_output_audits enable row level security;
revoke all on table public.ai_output_audits from anon, authenticated;
revoke all on sequence public.ai_output_audits_id_seq from anon, authenticated;
grant select, insert, update on table public.ai_output_audits to service_role;
grant usage, select on sequence public.ai_output_audits_id_seq to service_role;
